<?xml version="1.0"?>
<robot name="alpha" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Defining the colors used in this robot -->
    <material name="Black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="White">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="Blue">
        <color rgba="0 0 1 1"/>
    </material>

    <material name="Red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- Constants -->
    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="left" value="-1"/>
    <xacro:property name="right" value="1"/>
    <xacro:property name="back" value="-1"/>
    <xacro:property name="front" value="1"/>

    <!-- base link properties -->
    <xacro:property name="base_radius" value="0.5" />
    <xacro:property name="base_len" value="0.05" />

    <!-- motor link properties -->
    <xacro:property name="motor_width" value="0.02" />
    <xacro:property name="motor_len" value="0.05" />

    <!-- wheel link properties -->
    <xacro:property name="wheel_radius" value="0.03" />
    <xacro:property name="wheel_len" value="0.01" />

    <!-- link1 properties -->
    <xacro:property name="link1_width" value="0.03" />
    <xacro:property name="link1_len" value="0.08" />

    <!-- link2 properties -->
    <xacro:property name="link2_width" value="0.03" />
    <xacro:property name="link2_len" value="0.16" />

    <!-- link3 properties -->
    <xacro:property name="link3_width" value="0.03" />
    <xacro:property name="link3_len" value="0.08" />

    <!-- link4 properties -->
    <xacro:property name="link4_width" value="0.025" />
    <xacro:property name="link4_len" value="0.16" />

    <!-- link5 properties -->
    <xacro:property name="link5_width" value="0.03" />
    <xacro:property name="link5_len" value="0.06" />

    <!-- link6 properties -->
    <xacro:property name="link6_width" value="0.04" />
    <xacro:property name="link6_len" value="0.02" />

    <!-- Left gripper -->
    <xacro:property name="left_gripper_len" value="0.08" />
    <xacro:property name="left_gripper_width" value="0.01" />
    <xacro:property name="left_gripper_height" value="0.01" />

    <!-- Right gripper -->
    <xacro:property name="right_gripper_len" value="0.08" />
    <xacro:property name="right_gripper_width" value="0.01" />
    <xacro:property name="right_gripper_height" value="0.01" />

    <!-- Gripper frame -->
    <xacro:property name="grasp_frame_radius" value="0.001" />

    <!-- Inertial matrix macro-->
    <xacro:macro name="inertial_matrix" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- arm link and joint macro -->
    <xacro:macro name="arm_link" params="parent number color link_width link_len z_loc axis_x axis_y axis_z">
        <link name="link_${number}" >
            <visual>
                <origin xyz="0 0 ${link_len/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${link_width}" length="${link_len}"/>
                </geometry>
                <material name="${color}" />
            </visual>
            <collision>
                <origin xyz="0 0 ${link_len/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${link_width}" length="${link_len}"/>
                </geometry>
            </collision>
            <xacro:inertial_matrix mass="1"/>
        </link>

        <joint name="joint_${number}" type="revolute">
            <parent link="${parent}"/>
            <child link="link_${number}"/>
            <origin xyz="0 0 ${z_loc}" rpy="0 0 0" />
            <axis xyz="${axis_x} ${axis_y} ${axis_z}" />
            <limit effort="300" velocity="1" lower="${-M_PI/2}" upper="${M_PI/2}" />
            <dynamics damping="50" friction="1"/>
        </joint>
    </xacro:macro>

    <!-- motor link and joint macro-->
    <!-- loc = -1: left;    loc = 1: right  -->
    <xacro:macro name="motor_link" params="parent loc color link_width link_len y_loc z_loc">
        <link name="motor_${loc}" >
            <visual>
                <origin xyz="0 0 -${link_width/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${link_width} ${link_len} ${link_width}"/>
                </geometry>
                <material name="${color}" />
            </visual>
            <collision>
                <origin xyz="0 0 -${link_width/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${link_width} ${link_len} ${link_width}"/>
                </geometry>
            </collision>
            <xacro:inertial_matrix mass="1"/>
        </link>

        <joint name="joint_motor_${loc}" type="fixed">
            <parent link="${parent}"/>
            <child link="motor_${loc}"/>
            <origin xyz="0 ${loc*y_loc} ${z_loc}" rpy="0 0 0" />
        </joint>
    </xacro:macro>

    <!-- wheel link and joint macro -->
    <xacro:macro name="wheel_link" params="parent loc color link_width link_len y_loc z_loc">
        <link name="wheel_${loc}" >
            <visual>
                <origin xyz="0 ${loc*link_len/2} 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${link_width}" length="${link_len}"/>
                </geometry>
                <material name="${color}" />
            </visual>
            <collision>
                <origin xyz="0 ${loc*link_len/2} 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${link_width}" length="${link_len}"/>
                </geometry>
            </collision>
            <xacro:inertial_matrix mass="1"/>
        </link>

        <joint name="joint_wheel_${loc}" type="continuous">
            <parent link="${parent}"/>
            <child link="wheel_${loc}"/>
            <origin xyz="0 ${loc*y_loc} ${z_loc}" rpy="0 0 0" />
            <axis xyz="0 ${-loc} 0" />
            <dynamics damping="0.7"/>
        </joint>
    </xacro:macro>
    <!-- caster link and joint macro -->
    <xacro:macro name="caster_link" params="parent loc color link_width link_len x_loc z_loc">
        <link name="caster_${loc}" >
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${link_width}" length="${link_len}"/>
                </geometry>
                <material name="${color}" />
            </visual>
            <collision>
                <origin xyz="0 ${loc*link_len/2} 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${link_width}" length="${link_len}"/>
                </geometry>
            </collision>
            <xacro:inertial_matrix mass="1"/>
        </link>

        <joint name="joint_caster_${loc}" type="fixed">
            <parent link="${parent}"/>
            <child link="caster_${loc}"/>
            <origin xyz="${loc*x_loc} 0 ${z_loc}" rpy="0 0 0" />
        </joint>
    </xacro:macro>
    
    <!-- base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${wheel_radius+motor_width+base_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${base_radius}" length="${base_len}"/>
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin xyz="0 0 ${wheel_radius+motor_width+base_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${base_radius}" length="${base_len}"/>
            </geometry>
        </collision>
        <xacro:inertial_matrix mass="1"/>
    </link>
    <!-- motor link -->
    <motor_link parent="base_link" loc="${left}" color="Red" link_width="${motor_width}" link_len="${motor_len}" y_loc="${base_radius-motor_len/2}" z_loc="${wheel_radius+motor_width/2}"/>
    <motor_link parent="base_link" loc="${right}" color="Red" link_width="${motor_width}" link_len="${motor_len}" y_loc="${base_radius-motor_len/2}" z_loc="${wheel_radius+motor_width/2}"/>

    <!-- wheel link -->
    <wheel_link parent="motor_${left}" loc="${left}" color="Blue" link_width="${wheel_radius}" link_len="${wheel_len}" y_loc="${motor_len/2}" z_loc="${-motor_width/2}"/>
    <wheel_link parent="motor_${right}" loc="${right}" color="Blue" link_width="${wheel_radius}" link_len="${wheel_len}" y_loc="${motor_len/2}" z_loc="${-motor_width/2}"/>
    <caster_link parent="base_link" loc="${back}" color="Red" link_width="${wheel_radius}" link_len="${wheel_len}" x_loc="${base_radius/2}" z_loc="${wheel_radius}"/>
    <caster_link parent="base_link" loc="${front}" color="Red" link_width="${wheel_radius}" link_len="${wheel_len}" x_loc="${base_radius/2}" z_loc="${wheel_radius}"/>

    <!-- arm link -->
    <arm_link parent="base_link" number="1" color="Red" link_width="${link1_width}" link_len="${link1_len}" z_loc="${wheel_radius+motor_width/2+base_len}" axis_x="0" axis_y="0" axis_z="1"/>
    <arm_link parent="link_1" number="2" color="Blue" link_width="${link2_width}" link_len="${link2_len}" z_loc="${link1_len}" axis_x="0" axis_y="1" axis_z="0"/>
    <arm_link parent="link_2" number="3" color="Black" link_width="${link3_width}" link_len="${link3_len}" z_loc="${link2_len}" axis_x="0" axis_y="1" axis_z="0"/>
    <arm_link parent="link_3" number="4" color="Red" link_width="${link4_width}" link_len="${link4_len}" z_loc="${link3_len}" axis_x="0" axis_y="0" axis_z="1"/>
    <arm_link parent="link_4" number="5" color="Blue" link_width="${link5_width}" link_len="${link5_len}" z_loc="${link4_len}" axis_x="0" axis_y="1" axis_z="0"/>
    <arm_link parent="link_5" number="6" color="Black" link_width="${link6_width}" link_len="${link6_len}" z_loc="${link5_len}" axis_x="0" axis_y="0" axis_z="1"/>

    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
    <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>

        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

    <!-- Gripper link and joint -->
    <link name="gripper_finger_link1">
        <visual>
            <origin xyz="0.04 -0.03 0"/>
            <geometry>
                <box size="${left_gripper_len} ${left_gripper_width} ${left_gripper_height}" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin xyz="0.04 -0.03 0"/>
            <geometry>
                <box size="${left_gripper_len} ${left_gripper_width} ${left_gripper_height}" />
            </geometry>
        </collision>
        <xacro:inertial_matrix mass="1"/>
    </link>

    <link name="gripper_finger_link2">
        <visual>
            <origin xyz="0.04 -0.03 0"/>
            <geometry>
                <box size="${right_gripper_len} ${right_gripper_width} ${right_gripper_height}" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin xyz="0.04 -0.03 0"/>
            <geometry>
                <box size="${right_gripper_len} ${right_gripper_width} ${right_gripper_height}" />
            </geometry>
        </collision>
        <xacro:inertial_matrix mass="1"/>
    </link>

    <joint name="finger_joint1" type="prismatic">
        <parent link="link_6"/>
        <child link="gripper_finger_link1"/>
        <origin xyz="0.0 0 ${link6_len}" />
        <axis xyz="0 1 0" />
        <limit effort="100" lower="0.03" upper="0.06" velocity="1.0"/>
        <dynamics damping="50" friction="1"/>
    </joint>

    <joint name="finger_joint2" type="fixed">
        <parent link="link_6"/>
        <child link="gripper_finger_link2"/>
        <origin xyz="0.0 0 ${link6_len}" />
    </joint>

    <!-- Grasping frame -->
    <link name="grasping_frame"/>

    <joint name="grasping_frame_joint" type="fixed">
      <parent link="link_3"/>
      <child link="grasping_frame"/>
      <origin xyz="0.08 0 0" rpy="0 0 0"/>
    </joint>

    <!-- ////////////   Gazebo   //////////// -->
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="link_1">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="link_2">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="link_3">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="link_4">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="link_5">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="link_6">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="motor_1">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="motor_-1">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="wheel_1">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="wheel_-1">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="caster_-1">
        <material>Gazebo/Red</material>
    </gazebo>
    <gazebo reference="caster_1">
        <material>Gazebo/Red</material>
    </gazebo>
    <gazebo reference="gripper_finger_link1">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="gripper_finger_link2">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- Transmissions for ROS Control -->
    <xacro:macro name="transmission_block" params="joint_name">
        <transmission name="tran1">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor1">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>
    
    <xacro:transmission_block joint_name="joint_1"/>
    <xacro:transmission_block joint_name="joint_2"/>
    <xacro:transmission_block joint_name="joint_3"/>
    <xacro:transmission_block joint_name="joint_4"/>
    <xacro:transmission_block joint_name="joint_5"/>
    <xacro:transmission_block joint_name="joint_6"/>
    <xacro:transmission_block joint_name="joint_motor_-1"/>
    <xacro:transmission_block joint_name="joint_motor_1"/>
    <xacro:transmission_block joint_name="joint_caster_1"/>
    <xacro:transmission_block joint_name="joint_caster_-1"/>

    <xacro:transmission_block joint_name="finger_joint1"/>

    <transmission name="joint_wheel_1_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_wheel_1">
            <hardwareInterface>VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_1">
            <hardwareInterface>VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="joint_wheel_-1_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_wheel_-1">
            <hardwareInterface>VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_-1">
            <hardwareInterface>VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- ros_control plugin -->

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNamespace>/Alpha</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <legacyMode>true</legacyMode>
            <leftJoint>joint_wheel_-1</leftJoint>
            <rightJoint>joint_wheel_1</rightJoint>
            <wheelSeparation>${base_radius*2}</wheelSeparation>
            <wheelDiameter>${2*wheel_radius}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> 
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo> 
</robot>