controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_controller
    joints:
      - finger_joint1
  - name: fake_wheel_controller
    joints:
      - joint_wheel_0
      - joint_wheel_2