joints: {
    joint_1: {id: 1, neutral: 205, max_angle: 169.6, min_angle: -169.6, max_speed: 90},
    joint_2: {id: 2, max_angle: 134.6, min_angle: -134.6, max_speed: 90},
    joint_3: {id: 3, max_angle: 150.1, min_angle: -150.1, max_speed: 90},
    joint_4: {id: 4, max_angle: 150.1, min_angle: -150.1, max_speed: 90},
    joint_5: {id: 5, max_angle: 150.1, min_angle: -150.1, max_speed: 90},
    joint_6: {id: 6, max_angle: 360, min_angle: -360, max_speed: 90},
    finger_joint1: {id: 7, max_speed: 90},
    base_l_wheel_joint: {id: 8, max_speed: 90},
    base_r_wheel_joint: {id: 9, max_speed: 90},
}
controllers: {
    arm_controller: {type: follow_controller, joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6], action_name: arm_controller/follow_joint_trajectory, onboard: False }
}